import './globals.css'
import 'bootstrap/dist/css/bootstrap.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBarLogin from "../Components/Utility/NavBarLogin"
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Ecomarce',
  description: 'Generated by nextjs mobx ',
}

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBarLogin/>
        {children}
        </body>
    </html>
  )
}
